### ISSUE TITLE
Calculate and report simple signature

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#11]
We should come up with a simple signature that people can copy-paste.
The signature should include:
- elitr-testset commit ID (just a few digits, the short git commit ID, not the full one)
- possibly SLTev commit ID (again, just the short one)
  - I am not really sure 
- then the calculation flags (casing, mwerSegmenter, ...)
- and then metric name

Probably the detailed output should be as it is now, with "signature prefix" listed above the table. Something like:

```
Signature: SLTev_e3da41-elitrtestset_4a5d99
nnPC   WER    ...
...
```

The ``--simple`` output (see #8) should probably already concatenate it and show things like:
```
SLTev_e3da41-elitrtestset_4a5d99-nnPC-WER  ...
...
```

**Comment by mohammad2928** [comment]
It's done.
