### ISSUE TITLE
SLTev must be fully parallelizable 

### ISSUE THREAD

**Issue by mohammad2928** [ELITR/SLTev#13]
SLTev must be parallelizable and avoid generating temp files when we are using mwerSegmenter.
Also, there is a need for an alternative way instead of sharing mwerSegmenter. 

(Refers to issue #1 ).

**Comment by obo** [comment]
Rishu, could you please review the current code, test it and close this issue if all is good? Otherwise re-assign to Mohammad. Thanks, O.

**Comment by obo** [comment]
Matusi, I am adding you because you could also easily test this with your setup and report bugs or fix SLTev.

**Comment by obo** [comment]
Let's hope this is OK. Reopen if any strange effects due to race conditions appear.
