### ISSUE TITLE
Making install.sh  

### ISSUE THREAD

**Issue by mohammad2928** [ELITR/SLTev#14]
There is a need "install.sh" file to install all dependencies of SLTev (evaluation and MGIZA).    

(Refers to issue #1)

**Comment by srdecny** [comment]
A Dockerfile would also be nice.

**Comment by obo** [comment]
Did the pip-style installation resolve also this, i.e. are binary dependencies installed?

**Comment by mohammad2928** [comment]
Yes. 
For data files (e.g binary files or text files),  in the setup.py  "data_files" should be added and they will add to the installation path.

**Comment by obo** [comment]
I do not understand your message.
"Yes" means that binary files are installed.
"should be added" means that it is not yet ready.

**Comment by mohammad2928** [comment]
Sorry.
The binary file (mwerSegmenter) is installed.
