### ISSUE TITLE
Demo crashes, Broken pipe

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#22]
I got the following error with the fresh installation:
```
(your-env) 14:39 victoria SLTev$SLTev-scripts/SLTev -e my-evaluation-run-1
working directory is  my-evaluation-run-1/
Evaluating the file  my-evaluation-run-1/kaccNlwi6lUCEM.en.cs.slt  in terms of translation quality against  my-evaluation-run-1/kaccNlwi6lUCEM.cs.OSt
Traceback (most recent call last):
  File "SLTev-scripts/SLTev", line 194, in <module>
    evaluator(ostt=ostt, tt=tt, align=align, mt=submission_file, SLTev_home=sltev_home, simple=args.simple)
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev/SLTev/SLTev-scripts/evaluator.py", line 43, in evaluator
    references.append(read_tt(path))
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev/SLTev/SLTev-scripts/files_modules.py", line 41, in read_tt
    l = tokenize(line.strip())
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev/SLTev/your-env/lib/python3.6/site-packages/mosestokenizer/tokenizer.py", line 70, in __call__
    self.writeline(sentence)
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev/SLTev/your-env/lib/python3.6/site-packages/toolwrapper.py", line 141, in writeline
    self.stdin.write(line + "\n")
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <bound method ToolWrapper.__del__ of mosestokenizer.tokenizer.MosesTokenizer(['perl', '/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev/SLTev/your-env/lib/python3.6/site-packages/mosestokenizer/tokenizer-v1.1.perl', '-q', '-l', 'en', '-b', '-a'], encoding='utf-8', cwd=None)>
Traceback (most recent call last):
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev/SLTev/your-env/lib/python3.6/site-packages/toolwrapper.py", line 67, in __del__
    self.close()
  File "/lnet/spec/work/people/bojar/diplomka/granty/elitr/testing-sltev/SLTev/your-env/lib/python3.6/site-packages/toolwrapper.py", line 133, in close
    getattr(self, attr).close()
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by mohammad2928** [comment]
Hi Ondrej, 

I have tested SLTev in various systems and I did not reproduce this error !!

**Comment by obo** [comment]
Have you tested it also on ufal machines, e.g. victoria? I am still getting the same error, fresh SLTev, fresh venv. Following exactly the README.md instructions.

**Comment by pyRis** [comment]
@mohammad2928 Hi, the issue is that you need to put `wheel` package in the requirements list. It's not an issue of SLTev, seems more like a python installation procedure. 

I followed the instructions and was able to get the results with the additional step of `pip install wheel`.

**Comment by obo** [comment]
Is the order of pip installation important?

In the crashing test instance of mine, wheel was already installed:

```
...
BrokenPipeError: [Errno 32] Broken pipe
(your-env) 16:47 victoria SLTev$pip install wheel
Requirement already satisfied: wheel in ./your-env/lib/python3.6/site-packages (0.36.2)
(your-env) 16:47 victoria SLTev$SLTev/SLTev -e my-evaluation-run-1
working directory is  my-evaluation-run-1/
Evaluating the file  my-evaluation-run-1/kaccNlwi6lUCEM.en.cs.slt  in terms of translation quality against  my-evaluation-run-1/kaccNlwi6lUCEM.cs.OSt
Traceback (most recent call last):
...
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by mohammad2928** [comment]
@obo  
I have tested SLTev in ufal machines (victoria, geri, freki) and it runs without any problems. 
even, I have copied your .bashrc file to my home, and I did not reproduce "broken pip" error. 

Also, in the last SLTev commit, I have put SLTev in the pypi repo, and please install SLTev as follow:
...
pip  install SLTev
...

**Comment by obo** [comment]
Pip installation works for me, thanks!

The broken pipe remains. Strange.

**Comment by pyRis** [comment]
Hi, I tested the installation on various machines, it works, including sol2, sol6, blackbird.

The `wheel` package was to suppress another error, which evidently does gets suppressed automatically by resorting to setup.py and installing from source not the wheel package.

@obo Can you please try creating a different env-name other than `your-env` and pulling a fresh clone of the repo?

**Comment by obo** [comment]
This is really a problem of my machine. It worked with the same account (so same .bashrc) on a different machine. Strange.
