### ISSUE TITLE
use eprint instead of print for all non-output

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#23]
I added eprint() to utilities.py which prints output to STDERR instead of STDOUT.

Please scan the whole code of SLTev and change print() to eprint() in all cases where the message is *for the user* instead of *for subsequent processing*. So all warnings, errors, meta-information should go to STDERR, but scores (and also reported commitids) should go to STDOUT.

**Comment by mohammad2928** [comment]
@obo
Many thanks for very useful notations. 
Should the meta-information in the evaluation go to the STDERR (using eprint)? 
for example:

...
n ... not considering, not using
P ... considering Partial segments in delay and quality calculation(in addition to Complete segments)
T ... considering source Timestamps supplied with MT output
W ... segmenting by mWER segmenter (i.e. not segmenting by MT source timestamps)
A ... considering word alignment (by GIZA) to relax word delay (i.e. relaxing more than just linear delay calculation)
...

**Comment by obo** [comment]
This is questionable, but I vote for *yes*.

Thanks, O.

----- Original Message -----
> From: "Mohammad2928" <notifications@github.com>
> To: "ELITR/SLTev" <SLTev@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Mention" <mention@noreply.github.com>
> Sent: Wednesday, 3 February, 2021 09:08:40
> Subject: Re: [ELITR/SLTev] use eprint instead of print for all non-output (#23)

> @obo
> Many thanks for very useful notations.
> Should the meta-information in the evaluation go to the STDERR (using eprint)?
> for example:
> 
> ...
> n ... not considering, not using
> P ... considering Partial segments in delay and quality calculation(in addition
> to Complete segments)
> T ... considering source Timestamps supplied with MT output
> W ... segmenting by mWER segmenter (i.e. not segmenting by MT source timestamps)
> A ... considering word alignment (by GIZA) to relax word delay (i.e. relaxing
> more than just linear delay calculation)
> ...
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ELITR/SLTev/issues/23#issuecomment-772318141

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by mohammad2928** [comment]
If we push evaluation meta-informations to the STDERR, maybe we need to add them to the README or other files, because users should have knowledge about keys (e.g. nnWn) in the output scores.

**Comment by obo** [comment]
STDERR gets normally printed with STDOUT. So it would be the same for users but better for programmatic processing of the output.

----- Original Message -----
> From: "Mohammad2928" <notifications@github.com>
> To: "ELITR" <SLTev@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Mention" <mention@noreply.github.com>
> Sent: Wednesday, 3 February, 2021 09:19:17
> Subject: Re: [ELITR/SLTev] use eprint instead of print for all non-output (#23)

> If we push evaluation meta-informations to the STDERR, maybe we need to add them
> to the README or other files, because users should have knowledge about keys
> (e.g. nnWn) in the output scores.
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ELITR/SLTev/issues/23#issuecomment-772323783

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by mohammad2928** [comment]
It's done.

**Comment by obo** [comment]
Looks good. Thanks.
