### ISSUE TITLE
setup.py and requirements.txt duplicate the package dependencies

### ISSUE THREAD

**Issue by bhaddow** [ELITR/SLTev#24]
Both setup.py and requirements.txt have the list of package dependencies. They can easily get out of sync (filelock was missing from setup.py). I am unsure what the pythonic solution to this is.

**Comment by bhaddow** [comment]
They dependencies are also listed in the README, which is unnecessary. And the README says python 3.5, whereas setup says python 3.6.

**Comment by mzilinec** [comment]
Hello, I don't think there's any "preferred" solution, but I would do it simply like:
```python
with open('requirements.txt') as f:
    install_requires = f.read().splitlines()
#...
setup(
    install_requires = install_requires
)

```
