### ISSUE TITLE
Running SLTev generates a whole set of empty directories

### ISSUE THREAD

**Issue by bhaddow** [ELITR/SLTev#25]
I run the suggested demo, ie

```
SLTev -g SLTev-sample --outdir my-evaluation-run-1
SLTev -e my-evaluation-run-1/
```

This generates the `outdir` as expected, but also generates many directories with names that look like UUIDs. These are all empty

**Comment by mohammad2928** [comment]
I have fixed it.

**Comment by bhaddow** [comment]
Thanks!
