### ISSUE TITLE
Why is flicker a whole number?

### ISSUE THREAD

**Issue by bhaddow** [ELITR/SLTev#26]
When running the example, the average flicker is 7, which is suspiciously round. I cannot see how this is calculated - is it count_changed_content / WordCount ?

**Comment by mohammad2928** [comment]
Hi Barry,
Yes, it is count_changed_content / WordCount  and I have rounded it by using int(count_changed_content / WordCount)

**Comment by bhaddow** [comment]
It seems strange to round it when the other measures are not rounded.

**Comment by mohammad2928** [comment]
I will fix it in the next version.

**Comment by mohammad2928** [comment]
It's done.
