### ISSUE TITLE
Should wheel files be committed?

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#31]
I just spotted ``SLTev-1.0.4-py2.py3-none-any.whl`` in the root of the repo. Should it really be there? If wheel files are really needed in the repo, shouldn't we put them to a subdir?

**Comment by mohammad2928** [comment]
Hi, 
The WHL file is not needed and I will remove it. 
 Users can find the WHL file in the SLTev PyPI repo  (https://pypi.org/project/SLTev).   
I just put WHL in the root for easier access.

**Comment by obo** [comment]
Hi.
Who's easier access? Who needs it when?
I did not need the wheel when installing SLTev (it was downloaded automatically by pip, I assume), so I think it really should be removed.
Remember, these things grow big. Anything you put into a git repo **remains there forever**. So all the weight you are adding, we all will be carrying all the time. One has to think twice before adding things.
(If it *is* useful, it *should* be there. I just do not know python wheels.)
Thanks, O.

**Comment by mohammad2928** [comment]
I know, when users use pip for installation, whl file downloaded automatically, but they can use "pip install whl-file" instead of it. 
I have removed whl file in the last commit.
Thanks for your notes.

**Comment by mzilinec** [comment]
Hi, in my opinion: anything that can be automatically generated shouldn't be in the repo.
This should be done in .gitignore - there are template .gitignore files for python which already exclude files like .whl, cache etc.
You can for example copy and use this .gitignore file:
https://github.com/github/gitignore/blob/master/Python.gitignore
