### ISSUE TITLE
SLTev as regular python file

### ISSUE THREAD

**Issue by mzilinec** [ELITR/SLTev#34]
Hi, I just noticed that the main SLTev file doesn't have the .py suffix. This can cause problems when importing it as a Python module.
I don't think this is the right way to install executables. The best way is using "entry points", see [here](https://stackoverflow.com/questions/774824/explain-python-entry-points).
Example:
```python
# In setup.py
entry_points={
    'console_scripts': [
        'SLTev = sltev.sltev:main',
    ],
},
```
Also from Python standards:

> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

**Comment by mohammad2928** [comment]
Thanks Matus. 
improved.
