### ISSUE TITLE
Add sanity check of mosestokenizer

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#38]
The BrokenPipe problem referenced in #22 is due to malfunctioning mosestokenizer in my installation.
Please add a diagnosis: Before the first run of mosestokenizer (or after its installation during STLev installation?), please test if:

```
tokenize = MosesTokenizer('en')
tokenize('Hello World!')
```
returns ``['Hello', 'World', '!']``

If not, exit, explaining that mosestokenizer is badly installed. Do it in try-catch clause.

Ideally find a fix for mosestokenizer...

**Comment by mohammad2928** [comment]
I will apply in the next version (version 1.0.7).

**Comment by mohammad2928** [comment]
improved.
