### ISSUE TITLE
Add four demos: SLT, MT, ASR, increMT

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#39]
To resolve #33, please make 4 versions of ``SLTev-sample``:

- for SLT (the current one)
- for MT only
- for ASR only
- for incremental MT, i.e. fake timestamps added to MT-only version

The README should highlight what files are sample outputs for each version.
All the 4 demos should be tested regularly.
Thanks, O.

**Comment by mohammad2928** [comment]
The current SLTev-sample contains SLT and ASR files. 
My impression is as follows: 
1- an index for SLT (e.g SLTev-sample-with-slt)
2- an index for ASR (e.g SLTev-sample-with-asr)
3- an index for MT (e.g SLTev-sample-with-mt)
4- an index for IMT (e.g SLTev-sample-with-imt)

Also, in the README we have as follow (If I am wrong please correct me):

---
SLT Evaluation
description ... 

```
 SLTev -g SLTev-sample-with-slt --outdir my-evaluation
 SLTev -e my-evaluation
```
ASR Evaluation
...

MT Evaluation
...

IMT Evaluation
...

---

**Comment by obo** [comment]
Closing this issue, because the README.md illustrates all -- except IMT. Perhaps IMT is labelled ASRT? See #56.
