### ISSUE TITLE
Replace "microaverage"  and "macroaverage" with something more meaningful.

### ISSUE THREAD

**Issue by bhaddow** [ELITR/SLTev#41]
Hi 

In the results, both microaveraged and macroaveraged flicker are reported. I find these terms very opaque. I assume in one, the flicker is averaged across the sentence, and then across the document, whilst in the other, it is averaged across the document directly. But which is which?

Perhaps "mean sentence flicker" and "mean document flicker" are better (although still not that clear)

best
Barry

**Comment by obo** [comment]
Thanks for raising this. I like Barry's suggestions but I am still a little uncertain about them.
Would these be clearer?
* mean flicker across sentences
* mean flicker across whole documents
...sorry about the verbosity.

**Comment by mohammad2928** [comment]
Improved.
