### ISSUE TITLE
ISt or IStt?

### ISSUE THREAD

**Issue by Gldkslfmsd** [ELITR/SLTev#42]
> OSt ... original speech manually transcribed

> OStt ... original speech manually transcribed with word-level timestamps

> ISt ... IS manually transcribed with word-level timestamps

how do you call IS transcript WITHOUT timtestamps? ISt or IStt? Readme should be fixed.

**Comment by mohammad2928** [comment]
I updated README but we did not use IS and IStt and we can remove them from README terminology.
Thanks.

**Comment by mohammad2928** [comment]
Improved.

**Comment by Gldkslfmsd** [comment]
> In the following, we use this notation:

in what following? This is a last section of the README, nothing follows.

Is the section *Terminology and Abbreviations* really necessary?

ASR, SLT, MT -- does it work if these letters are capitalized in the file names? If not, make it lowercase.

**Comment by obo** [comment]
README.md seems clear to me now. SLTev does not mention ISt. The Terminology and Abbreviations is IMHO not harmful and it can help some, so I propose to keep it there.
