### ISSUE TITLE
faild typo

### ISSUE THREAD

**Issue by Gldkslfmsd** [ELITR/SLTev#43]
> evaluation for  man-orto-dev2/20090115.007_004_EN_Hannan.asr  faild, file  man-orto-dev2/20090115.OSt  is not exist

faild -> failed

**Comment by mohammad2928** [comment]
I will fix it in the new next version. 
Many thanks.

**Comment by mzilinec** [comment]
also is not exist -> does not exist

**Comment by mohammad2928** [comment]
Improved.
Thanks.
