### ISSUE TITLE
corpus-level aggregated scores

### ISSUE THREAD

**Issue by Gldkslfmsd** [ELITR/SLTev#45]
I want aggregated scores, e.g. WER weighted average by the length of gold transcript. Instead, SLTev produces 28 
*WER.out files and *BLEU.out. Should I aggregate the scores on my own? Why does the tool not doing it?

**Comment by mohammad2928** [comment]
Please clarify your opinion more. 
If you want to use standard output instead of producing output files we can add a parameter for doing it (e.g. --aggregate).

**Comment by Gldkslfmsd** [comment]
If it's there, then it's an undocumented feature. I haven't found it in readme.

**Comment by mohammad2928** [comment]
Improved.

**Comment by Gldkslfmsd** [comment]
yes, thanks!
