### ISSUE TITLE
typo in function name

### ISSUE THREAD

**Issue by Gldkslfmsd** [ELITR/SLTev#48]
https://github.com/ELITR/SLTev/blob/c8ee0a8d9f9c1757afd88d0e52069ce2b40c8b3e/SLTev/quality_modules.py#L10

-> document ?

**Comment by Gldkslfmsd** [comment]
https://github.com/ELITR/SLTev/blob/c8ee0a8d9f9c1757afd88d0e52069ce2b40c8b3e/SLTev/utilities.py#L233

-> submission

**Comment by Gldkslfmsd** [comment]
https://github.com/ELITR/SLTev/blob/c8ee0a8d9f9c1757afd88d0e52069ce2b40c8b3e/SLTev/utilities.py#L153
-> Indeces ?

https://github.com/ELITR/SLTev/blob/c8ee0a8d9f9c1757afd88d0e52069ce2b40c8b3e/SLTev/utilities.py#L158

-> sub-file ?

**Comment by Gldkslfmsd** [comment]
https://github.com/ELITR/SLTev/blob/1ccd4fc8dc58474a6d53990edc43066007183caf/SLTev/delay_modules.py#L245

**Comment by Gldkslfmsd** [comment]
https://github.com/ELITR/SLTev/blob/1ccd4fc8dc58474a6d53990edc43066007183caf/SLTev/ASRev.py#L118

-> mwersegmenter

**Comment by Gldkslfmsd** [comment]
https://github.com/ELITR/SLTev/blob/1ccd4fc8dc58474a6d53990edc43066007183caf/SLTev/ASRev.py#L118

-> mwersegmenter , and several times in this function.

This function seems copy-pasted from the previous. It's not good to use code repetitions.

**Comment by mohammad2928** [comment]
Improved. 
Many Thanks.

**Comment by obo** [comment]
Seems OK. Feel free to reopen or create new issues if more typos are found.
