### ISSUE TITLE
why python >= 3.7?

### ISSUE THREAD

**Issue by Gldkslfmsd** [ELITR/SLTev#49]
Hello,
I can't install the latest version of SLTev from PyPI because it requires python3.7, but I, and everybody on our cluster, have only 3.6.9. Is it really necessary to require it? You're using users because of it.

**Comment by Gldkslfmsd** [comment]
I found it's because jiwer installs numpy, and by default it's numpy==1.20, which requires python>=3.7.  

Maybe it could work with numpy==1.19.5 which is for python>=3.6 .

**Comment by mohammad2928** [comment]
Hi,
I have reduced the needed python version to 3.6. 
Please use the following version of SLTev:
SLTev==1.1.3

**Comment by Gldkslfmsd** [comment]
only reducing didn't work. See PR #50

**Comment by mohammad2928** [comment]
I will add numpy==1.19.5 to the install_requires of setup.py in the next version.

**Comment by obo** [comment]
@Matus: I successfully used SLTev with python 3.7.4 and 3.6.9 and it works for me. Please just confirm that the dependencies are made sensibly for both pythons and close this issue.
