### ISSUE TITLE
Consider dropping NLTK, consider adding sacreMoses for tokenization

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#5]
NLTK is quite a heavy dependence. All we want from it is tokenization.
We would probably be better off with sacreMoses (which also adds some useless bells and whistles like the progress bar).
Please discuss here.

**Comment by mohammad2928** [comment]
Hi Ondrej,
I have dropped NLTK in the commit by the name " NLTK dropped in quality calculation". Also, I have used **mosestokenizer** for tokenization.

**Comment by obo** [comment]
NLTK is still in requirements.txt
