### ISSUE TITLE
Fingerprint not shown when evaluation without elitr-testset

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#55]
I tested the standalone evaluation, ie. those from ``sample-data``.
All works well, but no fingerprint is shown.
In this situation, the fingerprint should say just the SLTev commit id and some dummy or N/A value for elitr-testset.

**Comment by obo** [comment]
Suggested signature for the case without elitr-testset: ``SLTev_e6d55ec-elitrtestset_NONE``.

**Comment by mohammad2928** [comment]
Improved.
