### ISSUE TITLE
Use pip install for SLTev; then put SLTev and ASRev to PATH

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#6]
Current installation can be still simplified (see how other small packages do it) so that the user would only do:
```
pip install SLTev
```
After that, ``SLTev`` and ``ASRev`` should be made available in the PATH directly.

**Comment by Gldkslfmsd** [comment]
Hi,
I have some experience with Python packages, and I can tell you that if you do it, it will have consequences:

- if you want the entry-points in the PATH the pythonic way, make it a package. You need to add setup.py, and maintain a form of the package: https://www.freecodecamp.org/news/build-your-first-python-package/ . You install it with `python3 setup.py install` to your path. It will complicate the imports of nearby scripts. Anytime you make a change you must reinstall it first to propagate the changes to the points under your path, and it's annoying while debugging.

- if you want your package installable via `pip install SLTev` by everyone on the Internet, you must upload it to PyPI: pypi.org . Anytime you make a change and want to pass it to everyone, you must make a new release and upload it to PyPI again.

- a simpler way for you, less simple for users: `pip install [some-form-of-url-to-your-github-repo]`.

**Comment by Gldkslfmsd** [comment]
- if you upload it to PyPI and want to make sure you really support all new Python versions, and not only 3.5, to encourage all kinds of users to use SLTev, use Travis CI.

**Comment by obo** [comment]
Done by Mohammad.
