### ISSUE TITLE
Using float values for timestamps gives unhelpful error

### ISSUE THREAD

**Issue by bhaddow** [ELITR/SLTev#63]
Hi

If I have floating point values in the timestamps, then I get the error message:
```
File XXX and line 0 is not in the proper format please correct this line as C/P 0 0 0 <text line> or it is empty"
```
The only way I could see what is happening is to examine the code. I would suggest that either (i) we allow floating point values; or (ii) we provide a better error message. Probably (ii) is better.

best,
Barry

**Comment by mohammad2928** [comment]
Hi Barry,

I have fixed this issue in the current version (1.1.9). 
I have used the (i) method because there is no need to force users to use just integer numbers for the time. 

Thanks, 
Mohammad
