### ISSUE TITLE
If mwerSegmenter fails, no error message is printed

### ISSUE THREAD

**Issue by bhaddow** [ELITR/SLTev#65]
Hi

If mwerSegmenter fails, then the exception is swallowed and no error message is printed. This is in evaluator.py, line 228

best
Barry

**Comment by sukantasen** [comment]
Passing `ignore_errors=True` to `shutil.rmtree()` https://github.com/ELITR/SLTev/blob/master/SLTev/files_modules.py#L319 prevents mwerSegmenter from failing.

**Comment by mohammad2928** [comment]
Hi Barry, 
Thanks, I added the exception message in the current version (1.1.9).  

Thanks,
Mohammad
