### ISSUE TITLE
Supporting Python 2

### ISSUE THREAD

**Issue by eebism** [ELITR/SLTev#68]
@mohammad2928 Please make SLTev compatible with Python 2. It can detect the language and run the corresponding one.

**Comment by mohammad2928** [comment]
Hi,

In the quality calculation, we have used the sacrebleu module which needs python3 or greater. So we can not use python2.  

But I will try to find an alternative module instead of the sacerbleu.

**Comment by bhaddow** [comment]
Since python 2 is no longer supported by python, what is the point? No-one should be using python 2 any more.

**Comment by obo** [comment]
I second to Barry, I also do struggle with python installation at times, but indeed, let's not promote python 2 any more.
