### ISSUE TITLE
Add ``--simple`` to show only some key scores

### ISSUE THREAD

**Issue by obo** [ELITR/SLTev#8]
The current output is too detailed for common use. Add ``--simple`` which would select only:
- doclevel sacreBLEU for MT quality
- mwerSegmenter case-insensitive WER for ASR quality
- one of the delays (probably mwerSegmenter proportional?) for latency
- one of the flickers for stability

**Comment by mohammad2928** [comment]
It's done. 
For SLT evaluation, the following scores will be shown:
0- Signature  
1- mwerSegmenter proportional without alignment
2- flicker size 
3- docAsAWhole sacreBLEU 
An example of SLT output:

        Signature:  SLTev_4e179b8-elitrtestset_3ba5c8d
        tot      Delay         PnWn                   170767.130
        tot      Flicker       count_changed_content  9389
        tot      sacreBLEU     docAsAWhole            10.783

Also, for ASR evaluation, the following scores will be shown:
0- Signature  
1- mwerSegmenter case-insensitive WER
An example of ASR output:

        Signature:  SLTev_4e179b8-elitrtestset_3ba5c8d
        PnWn  0.272
